### ISSUE TITLE
Import product bundles on Magento 2.2.x fails

### ISSUE THREAD

**Issue by wagnert** [techdivision/import-cli-simple#156]
When trying to import the product bundle from the sample data M2IF is throwing the following execption

```sh
[2018-10-19 16:42:06] logger/system.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`hoegl`.`catalog_product_bundle_option`, CONSTRAINT `CAT_PRD_BNDL_OPT_OPT_ID_SEQUENCE_PRD_BNDL_OPT_SEQUENCE_VAL` FOREIGN KEY (`option_id`) REFERENCES `sequence_product_bundle_option` (`sequenc) in /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Actions/Processors/AbstractBaseProcessor.php:146
Stack trace:
#0 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Actions/Processors/AbstractBaseProcessor.php(146): PDOStatement->execute(Array)
#1 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Actions/Processors/ProductBundleOptionCreateProcessor.php(63): TechDivision\Import\Actions\Processors\AbstractBaseProcessor->execute(Array, NULL)
#2 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Actions/ProductBundleOptionAction.php(66): TechDivision\Import\Product\Bundle\Actions\Processors\ProductBundleOptionCreateProcessor->execute(Array, NULL)
#3 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Actions/ProductBundleOptionAction.php(53): TechDivision\Import\Product\Bundle\Actions\ProductBundleOptionAction->create(Array)
#4 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Services/ProductBundleProcessor.php(457): TechDivision\Import\Product\Bundle\Actions\ProductBundleOptionAction->persist(Array)
#5 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Observers/BundleOptionObserver.php(200): TechDivision\Import\Product\Bundle\Services\ProductBundleProcessor->persistProductBundleOption(Array)
#6 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Observers/BundleOptionObserver.php(90): TechDivision\Import\Product\Bundle\Observers\BundleOptionObserver->persistProductBundleOption(Array)
#7 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product/src/Observers/AbstractProductImportObserver.php(55): TechDivision\Import\Product\Bundle\Observers\BundleOptionObserver->process()
#8 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Subjects/AbstractSubject.php(860): TechDivision\Import\Product\Observers\AbstractProductImportObserver->handle(Object(TechDivision\Import\Product\Bundle\Ee\Subjects\EeBundleSubject))
#9 [internal function]: TechDivision\Import\Subjects\AbstractSubject->importRow(Array)
#10 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(149): call_user_func(Array, Array)
#11 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(135): TechDivision\Import\Adapter\Goodby\Interpreter->delegate(Array, Array)
#12 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(74): TechDivision\Import\Adapter\Goodby\Interpreter->notify(Array)
#13 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Lexer.php(110): TechDivision\Import\Adapter\Goodby\Interpreter->interpret(Array)
#14 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/CsvImportAdapter.php(80): TechDivision\Import\Adapter\Goodby\Lexer->parse('projects/hoegl/...', Object(TechDivision\Import\Adapter\Goodby\Interpreter))
#15 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Subjects/AbstractSubject.php(750): TechDivision\Import\Adapter\CsvImportAdapter->import(Array, 'projects/hoegl/...')
#16 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Plugins/SubjectExecutor.php(107): TechDivision\Import\Subjects\AbstractSubject->import('5655a181-f0fd-4...', 'projects/hoegl/...')
#17 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(213): TechDivision\Import\Plugins\SubjectExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject), Array, '5655a181-f0fd-4...', 'projects/hoegl/...')
#18 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(112): TechDivision\Import\Plugins\SubjectPlugin->processSubject(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject))
#19 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-app-simple/src/Simple.php(623): TechDivision\Import\Plugins\SubjectPlugin->process()
#20 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-cli-simple/src/Command/AbstractImportCommand.php(103): TechDivision\Import\App\Simple->process()
#21 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Command/Command.php(241): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportProductsCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/bootstrap.php(39): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/bin/import-pro.php(54): require('/Users/wagnert/...')
#27 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/bin/import-pro(2): require('/Users/wagnert/...')
#28 {main}

Next PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`hoegl`.`catalog_product_bundle_option`, CONSTRAINT `CAT_PRD_BNDL_OPT_OPT_ID_SEQUENCE_PRD_BNDL_OPT_SEQUENCE_VAL` FOREIGN KEY (`option_id`) REFERENCES `sequence_product_bundle_option` (`sequenc) when executing SQL "INSERT
               INTO catalog_product_bundle_option
                    (parent_id,
                     required,
                     position,
                     type)
             VALUES (4037,
                     1,
                     1,
                     radio)" in /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Actions/Processors/AbstractBaseProcessor.php:161
Stack trace:
#0 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Actions/Processors/ProductBundleOptionCreateProcessor.php(63): TechDivision\Import\Actions\Processors\AbstractBaseProcessor->execute(Array, NULL)
#1 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Actions/ProductBundleOptionAction.php(66): TechDivision\Import\Product\Bundle\Actions\Processors\ProductBundleOptionCreateProcessor->execute(Array, NULL)
#2 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Actions/ProductBundleOptionAction.php(53): TechDivision\Import\Product\Bundle\Actions\ProductBundleOptionAction->create(Array)
#3 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Services/ProductBundleProcessor.php(457): TechDivision\Import\Product\Bundle\Actions\ProductBundleOptionAction->persist(Array)
#4 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Observers/BundleOptionObserver.php(200): TechDivision\Import\Product\Bundle\Services\ProductBundleProcessor->persistProductBundleOption(Array)
#5 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product-bundle/src/Observers/BundleOptionObserver.php(90): TechDivision\Import\Product\Bundle\Observers\BundleOptionObserver->persistProductBundleOption(Array)
#6 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-product/src/Observers/AbstractProductImportObserver.php(55): TechDivision\Import\Product\Bundle\Observers\BundleOptionObserver->process()
#7 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Subjects/AbstractSubject.php(860): TechDivision\Import\Product\Observers\AbstractProductImportObserver->handle(Object(TechDivision\Import\Product\Bundle\Ee\Subjects\EeBundleSubject))
#8 [internal function]: TechDivision\Import\Subjects\AbstractSubject->importRow(Array)
#9 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(149): call_user_func(Array, Array)
#10 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(135): TechDivision\Import\Adapter\Goodby\Interpreter->delegate(Array, Array)
#11 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(74): TechDivision\Import\Adapter\Goodby\Interpreter->notify(Array)
#12 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/Goodby/Lexer.php(110): TechDivision\Import\Adapter\Goodby\Interpreter->interpret(Array)
#13 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Adapter/CsvImportAdapter.php(80): TechDivision\Import\Adapter\Goodby\Lexer->parse('projects/hoegl/...', Object(TechDivision\Import\Adapter\Goodby\Interpreter))
#14 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Subjects/AbstractSubject.php(750): TechDivision\Import\Adapter\CsvImportAdapter->import(Array, 'projects/hoegl/...')
#15 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Plugins/SubjectExecutor.php(107): TechDivision\Import\Subjects\AbstractSubject->import('5655a181-f0fd-4...', 'projects/hoegl/...')
#16 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(213): TechDivision\Import\Plugins\SubjectExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject), Array, '5655a181-f0fd-4...', 'projects/hoegl/...')
#17 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(112): TechDivision\Import\Plugins\SubjectPlugin->processSubject(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject))
#18 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-app-simple/src/Simple.php(623): TechDivision\Import\Plugins\SubjectPlugin->process()
#19 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/techdivision/import-cli-simple/src/Command/AbstractImportCommand.php(103): TechDivision\Import\App\Simple->process()
#20 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Command/Command.php(241): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportProductsCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/bootstrap.php(39): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/bin/import-pro.php(54): require('/Users/wagnert/...')
#26 /Users/wagnert/Workspace_Idea/techdivision/import-cli-pro/bin/import-pro(2): require('/Users/wagnert/...')
#27 {main}
```

**Comment by wagnert** [comment]
Resolved with version 2.0.0
