### ISSUE TITLE
Import Url key on Magento 2.2.6

### ISSUE THREAD

**Issue by deiserh** [techdivision/import-cli-simple#157]
If I update products on import with an url_key in the import file the following error occure:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'key.html-' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID' in /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Actions/Processors/AbstractBaseProcessor.php:146
Stack trace:
#0 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Actions/Processors/AbstractBaseProcessor.php(146): PDOStatement->execute(Array)
#1 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Actions/Processors/UrlRewriteCreateProcessor.php(58): TechDivision\Import\Actions\Processors\AbstractBaseProcessor->execute(Array, NULL)
#2 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Actions/UrlRewriteAction.php(65): TechDivision\Import\Actions\Processors\UrlRewriteCreateProcessor->execute(Array, NULL)
#3 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Actions/UrlRewriteAction.php(52): TechDivision\Import\Actions\UrlRewriteAction->create(Array)
#4 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-product-url-rewrite/src/Services/ProductUrlRewriteProcessor.php(413): TechDivision\Import\Actions\UrlRewriteAction->persist(Array, NULL)
#5 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteObserver.php(654): TechDivision\Import\Product\UrlRewrite\Services\ProductUrlRewriteProcessor->persistUrlRewrite(Array)
#6 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteObserver.php(279): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteObserver->persistUrlRewrite(Array)
#7 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteUpdateObserver.php(58): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteObserver->process()
#8 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteObserver.php(253): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteUpdateObserver->process()
#9 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Subjects/AbstractSubject.php(860): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteObserver->handle(Object(TechDivision\Import\Product\UrlRewrite\Subjects\UrlRewriteSubject))
#10 [internal function]: TechDivision\Import\Subjects\AbstractSubject->importRow(Array)
#11 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(149): call_user_func(Array, Array)
#12 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(135): TechDivision\Import\Adapter\Goodby\Interpreter->delegate(Array, Array)
#13 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(74): TechDivision\Import\Adapter\Goodby\Interpreter->notify(Array)
#14 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Adapter/Goodby/Lexer.php(110): TechDivision\Import\Adapter\Goodby\Interpreter->interpret(Array)
#15 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Adapter/CsvImportAdapter.php(80): TechDivision\Import\Adapter\Goodby\Lexer->parse('/home/kunde/imp...', Object(TechDivision\Import\Adapter\Goodby\Interpreter))
#16 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Subjects/AbstractSubject.php(750): TechDivision\Import\Adapter\CsvImportAdapter->import(Array, '/home/kunde/imp...')
#17 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Plugins/SubjectExecutor.php(107): TechDivision\Import\Subjects\AbstractSubject->import('57e8d05c-adb0-4...', '/home/kunde/imp...')
#18 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(213):TechDivision\Import\Plugins\SubjectExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject), Array, '57e8d05c-adb0-4...', '/home/kunde/imp...')
#19 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(112):TechDivision\Import\Plugins\SubjectPlugin->processSubject(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject))
#20 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-app-simple/src/Simple.php(623): TechDivision\Import\Plugins\SubjectPlugin->process()
#21 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-cli-simple/src/Command/AbstractImportCommand.php(103): TechDivision\Import\App\Simple->process()
#22 /var/www/test.ci.tdintern.de/releases/20/vendor/symfony/console/Command/Command.php(245): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/test.ci.tdintern.de/releases/20/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/test.ci.tdintern.de/releases/20/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportProductsCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/test.ci.tdintern.de/releases/20/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-cli-pro/bootstrap.php(39): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-cli-pro/bin/import-pro.php(54): require('/var/www/test.c...')
#28 /var/www/test.ci.tdintern.de/releases/20/vendor/techdivision/import-cli-pro/bin/import-pro(2): require('/var/www/test.c...')
#29 {main}
```

**Comment by wagnert** [comment]
Seems to be a project specific issue
