### ISSUE TITLE
Call to a member function getSystemLogger() on null

### ISSUE THREAD

**Issue by denvit** [techdivision/import-cli-simple#263]
**Describe the bug**
I’m getting this error when importing products and when the import file (the ones that I prepare for M2IF) don’t have the data and has only CSV headers (product attributes)

```
[2021-02-23 08:54:42] logger/system.INFO: Now start import with serial 033fe703-1078-4bab-a43c-c712a99a2089 [none => create-ok-files]  {"serial":"033fe703-1078-4bab-a43c-c712a99a2089","memory_peak_usage":"18 MB"}
[2021-02-23 08:54:42] logger/system.INFO: Execution time for operation with serial 033fe703-1078-4bab-a43c-c712a99a2089 in 0.020036 s  {"serial":"033fe703-1078-4bab-a43c-c712a99a2089","memory_peak_usage":"18 MB"}
[2021-02-23 08:54:42] logger/system.INFO: Found no files to archive  {"serial":"033fe703-1078-4bab-a43c-c712a99a2089","memory_peak_usage":"18 MB"}
[2021-02-23 08:54:42] logger/system.INFO: Successfully executed command import:create:ok-file with serial 033fe703-1078-4bab-a43c-c712a99a2089 in 00:00:00 s  {"serial":"033fe703-1078-4bab-a43c-c712a99a2089","memory_peak_usage":"18 MB"}
[2021-02-23 08:54:43] logger/system.INFO: Now start import with serial 7b904055-2b3b-463b-92e2-ed4b77181436 [catalog_product => add-update]  {"serial":"7b904055-2b3b-463b-92e2-ed4b77181436","memory_peak_usage":"18 MB"}
[2021-02-23 08:54:44] logger/system.INFO: Now start processing file "product-import_20210223_160.csv" {"operation-name":"general/catalog_product/collect-data"} {"serial":"7b904055-2b3b-463b-92e2-ed4b77181436","memory_peak_usage":"46 MB"}
[2021-02-23 08:54:44] logger/system.NOTICE: Successfully processed file "product-import_20210223_160.csv" with "0" lines (skipped "0") in "0.001968" s {"operation-name":"general/catalog_product/collect-data"} {"serial":"7b904055-2b3b-463b-92e2-ed4b77181436","memory_peak_usage":"46 MB"}
[2021-02-23 08:54:44] logger/system.ERROR: Uncaught Error: Call to a member function getSystemLogger() on null in /Users/denis/Sites/magento/vendor/techdivision/import/src/Observers/AbstractObserver.php:307
Stack trace:
#0 /Users/denis/Sites/magento/vendor/techdivision/import/src/Observers/GenericHookAwareColumnCollectorObserver.php(187): TechDivision\Import\Observers\AbstractObserver->getSystemLogger()
#1 /Users/denis/Sites/magento/vendor/techdivision/import/src/Subjects/AbstractSubject.php(702): TechDivision\Import\Observers\GenericHookAwareColumnCollectorObserver->tearDown('7b904055-2b3b-4...')
#2 /Users/denis/Sites/magento/vendor/techdivision/import/src/Subjects/SubjectExecutor.php(160): TechDivision\Import\Subjects\AbstractSubject->tearDown('7b904055-2b3b-4...')
#3 /Users/denis/Sites/magento/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(168): TechDivision\Import\Subjects\SubjectExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject), Array, '7b904055-2b3b-4...', '/Users/denis/Si...')
#4 /Users/denis/S  {"serial":"7b904055-2b3b-463b-92e2-ed4b77181436","memory_peak_usage":"46 MB"}
```

**To Reproduce**
1. Create an M2IF ready CSV file for import with only CSV headers (product attributes) data:
sku,attribute_set_code,product_websites,store,categories,name,url_key,description,short_description,weight,status,tax_class_id,visibility,price
2. Run: vendor/bin/import-simple import:create:ok-file  
3. Run: vendor/bin/import-simple import:products  
4. See an error

**Expected behavior**
With version 3.8.34 it works ok and the import of products goes through.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 
 - Browser /
 - Version of M2IF: 3.8.41
 - Magento version: 2.3.5-p2

**Comment by pathmissing** [comment]
Hi @denvit, thank you for reporting this issue! We will have a look.
Issue tracked internally as PAC-362.

**Comment by Bullitt300** [comment]
@Mardl this should be fixed in version https://github.com/techdivision/import/releases/tag/16.8.6
